### ISSUE TITLE
define ITN compat not chaning half life

### ISSUE THREAD

**Issue by TAlonsoAmor** [SwissTPH/r-openMalariaUtilities#25]
This code 
```
define_ITN_compat(
  baseList = baseList, component = "histITN_10", mosqs = mosqs, hist = TRUE,
  resist = FALSE, halflife = 10, versionnum = versionnum
)
```

returns this snippet
```
    <component id="histITN_10" name="histITN_10">
        <ITN>
          <usage value="1"/>
          <holeRate CV="0" distr="lognormal" mean="0"/>
          <ripRate CV="0" distr="lognormal" mean="0"/>
          <ripFactor value="0"/>
          <initialInsecticide mean="55.5" SD="14" distr="normal"/>
          <insecticideDecay function="step" L="1" CV="0"/>
          <attritionOfNets function="step" L="1"/>
```

If halflife = 10 according to the doc of define_ITN_compat, the snippet should be `<attritionOfNets function="step" L="10"/>`

**Comment by ChristianSelinger** [comment]
This was copy-paste from munirflow
https://git.scicore.unibas.ch/idm/countrymodelling/munirflow/-/blob/master/R/munirflow_0_base.R#L2380
Roland made a REVIEW comment:
https://github.com/SwissTPH/r-openMalariaUtilities/blob/develop/R/xml_interventions_define.R#L719

The hist=T flag will set L=1 (I guess this means that you would update your effective coverage from country data every year, hence no attrition)...if L is the initial value of the function, I guess that L=10 would not make sense for "usage attrition", right? Please let me know if you think that it is otherwise or that we should improve on this...
